config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#show'

  get '/auth/github', as: :github_login
  get '/auth/github/callback', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout
  resources :followers, only: [:index]
  resources :followings, only: [:index]
  resources :stars, only: [:index]

  get ':nickname_slug', to: 'users#show', as: :dashboard
end

app/models/events.rb
class Events < OpenStruct

  def self.all(service)
    service.push_events.map do |event|
      Events.new(event) if event["type"].include?("Push")
    end.compact
  end

  def self.all_for_following(service, username)
    service.other_user_events(username).map do |event|
      Events.new(event) if event["type"].include?("Push")
    end.compact
  end

  def username
    self.actor["login"]
  end

  def repo_name
    self.repo["name"]
  end

  def repo_url
    self.repo["url"]
  end

  def commit_message
    self.payload["commits"][0]["message"]
  end

  def author_name
    self.payload["commits"][0]["author"]["name"]
  end

  def formatted_time
    t = Time.parse(self.created_at)
    t.strftime("%m/%d/%Y at %I:%M%p")
  end

  def event_description
    "Commit of '#{commit_message}' by #{username} on #{formatted_time} for #{repo_name} repo."
  end
end

app/models/followers.rb
class Followers < OpenStruct
  def self.all(service)
    service.followers.map { |follower| Followers.new(follower) }
  end
end

app/models/following.rb
class Following < OpenStruct
  def self.all(service)
    service.following.map { |following| Following.new(following) }
  end
end

app/models/organizations.rb
class Organizations < OpenStruct
  def self.all(service)
    service.orgs.map {|org| Organizations.new(org)}
  end
end

app/models/repos.rb
class Repos < OpenStruct
  def self.all(service)
    service.repositories.map { |repo| Repos.new(repo) }
  end
end

app/models/service_accessor.rb
class ServiceAccessor
  attr_reader :user

  def initialize(current_user)
    @user = current_user
  end

  def service
    @service ||= UserService.new(user)
  end

  def followers
    Followers.all(service)
  end

  def following
    Following.all(service)
  end

  def starred
    Starred.all(service)
  end

  def repos
    Repos.all(service)
  end

  def organizations
    Organizations.all(service)
  end

  def events
    Events.all(service)
  end

  def following_events
    followers.map do |person|
      Events.all_for_following(service, person.login)
    end.flatten
  end
end

app/models/starred.rb
class Starred < OpenStruct
  def self.all(service)
    service.starred.map { |starred| Starred.new(starred) }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :create_slug

  def create_slug
    self.nickname_slug = self.nickname.parameterize
  end

  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid                  = auth_info['uid']
      new_user.name                 = auth_info['info']['name']
      new_user.nickname             = auth_info['info']['nickname']
      new_user.avatar               = auth_info['info']['image']
      new_user.oauth_token          = auth_info['credentials']['token']
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  add_flash_types :success, :info, :warning, :danger

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  def index
    @followers = ServiceAccessor.new(current_user).followers
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  def index
    @following = ServiceAccessor.new(current_user).following
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to dashboard_path(user.nickname_slug)
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/stars_controller.rb
class StarsController < ApplicationController
  def index
    @stars = ServiceAccessor.new(current_user).starred
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if current_user
      @git_accessor = ServiceAccessor.new(current_user)
    else
      flash[:notice] = "You must be logged in to view this page"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/followers/index.html.erb
<div class="container">
  <h1 class='text-center'>Followers</h1><br>

  <% @followers.each do |person| %>
    <div class="col-md-4">
      <%= image_tag(person.avatar_url, size: '200x200') %>
      <%= link_to person.login, person.html_url %>
    </div>
  <% end %>

</div>

app/views/followings/index.html.erb
<div class="container">
  <h1 class='text-center'>Following</h1><br>

  <% @following.each do |person| %>
    <div class="col-md-4">
      <%= image_tag(person.avatar_url, size: '200x200') %>
      <%= link_to person.login, person.html_url %>
    </div>
  <% end %>

</div>

app/views/homes/show.html.erb
<div class="container sign-in magic-center">
  <% if current_user %>
    <h1>Welcome, Check Out Your Github Profile</h1>
    <%= button_to "My Info", dashboard_path(current_user.nickname_slug), method: :get, class: "btn btn-info btn-lg" %>
  <% else %>
    <h1>Welcome, Sign In With Github</h1>
    <%= button_to "Login with Github", github_login_path, method: :get, class: "btn btn-info btn-lg" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>APICurious</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |type, message| %>
  <div class="alert alert-<%= type %> text-center alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span></button>
    <%= sanitize(message) %>
  </div>
  <% end %>

<%= yield %>

</body>
</html>

app/views/stars/index.html.erb
<div class="container">
  <h1 class='text-center'>Starred Repos</h1><br>
  <ul>
    <% @stars.each do |repo| %>
        <li><%= link_to repo.name, repo.svn_url %></li>
    <% end %>
  </ul>
</div>

app/views/users/show.html.erb
<div class="container user">

  <div class="row well ">
    <h1 class="text-center">Hello, <%= current_user.name %></h1>
    <div class="image col-md-5"><%= image_tag(current_user.avatar, size: '200x200') %></div>
    <div class="col-md-7">
      <h2><%= link_to @git_accessor.followers.count, followers_path %> Followers,
      <%= link_to @git_accessor.following.count, followings_path %> Following,
      <%= link_to @git_accessor.starred.count, stars_path %> Starred</h2>
      <%= button_to "Logout", logout_path, method: :delete, class: 'btn btn-info' %>
    </div>
  </div>

  <div class="user-tabs">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a href="#repos" aria-controls="home" role="tab" data-toggle="tab">Your Repos</a></li>
      <li role="presentation"><a href="#organizations" aria-controls="profile" role="tab" data-toggle="tab">Organizations</a></li>
      <li role="presentation"><a href="#yourfeed" aria-controls="messages" role="tab" data-toggle="tab">Your Recent Activity</a></li>
      <li role="presentation"><a href="#othersfeed" aria-controls="settings" role="tab" data-toggle="tab">Recent Activity - Following</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="repos">
        <ul>
          <% @git_accessor.repos.each do |repo| %>
            <li><%= link_to repo.name, repo.html_url, target: "blank" %></li>
          <% end %>
        </ul>
      </div>

      <div role="tabpanel" class="tab-pane" id="organizations">
        <ul>
          <h2>Organizations:</h2>
          <% @git_accessor.organizations.each do |org| %>
          <li><%= link_to org.login, org.url %></li>
          <% end %>
        </ul>
      </div>

      <div role="tabpanel" class="tab-pane" id="yourfeed">
        <ul>
          <h2>Events For Logged In User</h2>
          <% @git_accessor.events.each do |event| %>
            <li><%= event.event_description %></li>
          <% end %>
        </ul>
      </div>

      <div role="tabpanel" class="tab-pane" id="othersfeed">
        <ul>
          <% @git_accessor.following_events.each do |event| %>
              <li> <%= event.event_description %> </li>
          <% end %>
         </ul>
      </div>
    </div>
  </div>
</div>